<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>NotepadJM</AssemblyName>
    <RootNamespace>NotepadJM</RootNamespace>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <Version>2.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\AppIcon.ico" />
  </ItemGroup>
</Project>
